spring:
  application:
    name: resouce-web-app
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: 124.71.13.176:8848 # Nacos 服务器地址
        namespace: dev # Nacos 命名空间
  sentinel:
    transport:
      dashboard: localhost:8080
  sleuth:
    enabled: false

server:
  port: 38087

# 配置swagger
# Swagger 配置项
swagger:
  title: 资源服务
  description: 统一的资源服务
  version: 1.0.0
  base-package: com.db.chaomaxs.resourceweb.controller

# 服务提供者调用
chaomax:
  resource:
    serviceId: resource-service

#鉴权相关
auth:
  serviceId: auth-service-xiaofeng
  user:
    token-header: Authorization
  client:
    id: resource-web-app  #不填则默认读取spring.application.name
    secret: 123456

