spring:
  application:
    name: company-web-app-xiaofeng
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: 124.71.13.176:8848 # Nacos 服务器地址
        namespace: dev # Nacos 命名空间
  sentinel:
    transport:
      dashboard: localhost:8080
  sleuth:
    enabled: false
sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: false

server:
  port: 38084

# 配置swagger
# Swagger 配置项
swagger:
  title: 企业端服务
  description: 企业端服务接口
  version: 1.0.0
  base-package: com.db.chaomaxs.positionwantedweb.controller

# 服务提供者调用
chaomax:
  company:
    serviceId: company-service-xiaofeng
  position:
    serviceId: position-service-xiaofeng
  system:
    serviceId: system-service-xiaofeng
  user:
    serviceId: user-service-xiaofeng
  resource:
    serviceId: resource-service-xiaofeng


#鉴权相关
auth:
  serviceId: auth-service
  user:
    token-header: Authorization
  client:
    id: company-web-app-xiaofeng  #不填则默认读取spring.application.name
    secret: 123456
