spring:
  application:
    name: company-service-hlf
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: 124.71.13.176:8848 # Nacos 服务器地址
        namespace: dev # Nacos 命名空间
  sentinel:
    transport:
      dashboard: localhost:8080
  sleuth:
    enabled: false

server:
  port: 8763

# 自定义Jwt认证服务
jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

auth:
  serviceId: auth-service-xiaofeng
  user:
    token-header: Authorization
  client:
    id: company-service-xiaofeng  #不填则默认读取spring.application.name
    secret: 123456

logging:
  level:
    com.db.chaomaxs.companyservice.dal.mysql.mapper: debug
