spring:
  application:
    name: system-service-xiaofeng
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 服务器地址
        namespace: dev # Nacos 命名空间
  sentinel:
    transport:
      dashboard: localhost:8080
  sleuth:
    enabled: false

server:
  port: 8768

auth:
  serviceId: auth-service-xiaofeng
  user:
    token-header: Authorization
  client:
    id: system-service-xiaofeng  #不填则默认读取spring.application.name
    secret: 123456

logging:
  level:
    com.github.xf717.systemservice.dal.mysql.mapper: debug
