logging:
  level:
    #        tk.mybatis: DEBUG
    com.github.xf717.security.auth: DEBUG
spring:
  application:
    name: auth-service-xiaofeng
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  redis:
    database: 2
    host: 124.71.13.176
    password: sentence@123456
    jedis:
      pool:
        max-active: 20
  datasource:
    name: auth-service
    url: jdbc:mysql://${MYSQL_HOST:124.71.13.176}:${MYSQL_PORT:3306}/system-service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    username: root
    password: sentence@123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  cloud:
    nacos:
      discovery:
        server-addr: 124.71.13.176:8848
        namespace: dev
  sentinel:
    transport:
      dashboard: localhost:8080
  sleuth:
    enabled: false
sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: false

mybatis:
  basepackage: com.github.xf717.security.auth.mapper
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/*.xml"

server:
  port: 8762

# 必须配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 100000
  ConnectTimeout: 100000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: heapdump,dump,threaddump,configprops,env
  security:
    enabled: true

# 自定义Jwt认证服务
jwt:
  token-header: Authorization
  expire: 259200  #单位秒
  rsa-secret: xx1WET12^%3^(WE45

auth:
  serviceId: auth-service-xiaofeng
  user:
    token-header: Authorization
  client:
    id: auth-service  #不填则默认读取spring.application.name
    secret: 123456

